name: flutterflip
description: A Reversi game built in Flutter.

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  async: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0

flutter:

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          style: italic
